In [2]:
print("Twinkle, twinkle, little star, \n\tHow I wonder what you are! \n\t\tUp above the world so high, \n\t\tLike a diamond in the sky. \nTwinkle, twinkle, little star, \n\tHow I wonder what you are!")

Twinkle, twinkle, little star, 
	How I wonder what you are! 
		Up above the world so high, 
		Like a diamond in the sky. 
Twinkle, twinkle, little star, 
	How I wonder what you are!


In [3]:
import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)

Python version
3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)


In [4]:
import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d %H:%M:%S"))

Current date and time : 
2018-07-31 10:03:26


In [5]:
import datetime
now = datetime.datetime.now()
print(now)

2018-07-31 10:04:04.930161


In [6]:
# pi * r**2
pi  = 3.14
radius = 5
area = pi * radius ** 2
print(area)

78.5


In [7]:
from math import pi
r = float(input ("Input the radius of the circle : "))
print ("The area of the circle with radius " + str(r) + " is: " + str(pi * r**2))

Input the radius of the circle : 15
The area of the circle with radius 15.0 is: 706.8583470577034


In [8]:
from math import pi
radius = float(input("Input radius: "))
print("Area of circle is " + str(pi*radius**2))

Input radius: 5
Area of circle is 78.53981633974483


In [10]:
firstname = str(input("Enter First name: "))
lastname = str(input("Enter Last name: "))
print(lastname +" "+firstname)

Enter First name: Adi
Enter Last name: Man
Man Adi


In [17]:
sample = str(input("Enter comma seperated values: "))
List = sample.split(",")
print("List: ",List)
tuple=tuple(List)
print("Tuple:",tuple)


Enter comma seperated values: 1,2,3,4,5
List:  ['1', '2', '3', '4', '5']
Tuple: ('1', '2', '3', '4', '5')


In [20]:
sample = str(input("Enter the file name: "))
extn=sample.split(".")
print("Extension is: ", extn[-1])

Enter the file name: abc.java
Extension is:  java


In [24]:
color_list = ["Red","Green","White" ,"Black"]
print(color_list[0],color_list[-1])

Red Black


In [27]:
move_out_date = (31,7,2018)
print( "The move out will start from : %i / %i / %i"%move_out_date)

The move out will start from : 31 / 7 / 2018


In [31]:
n = str(input("Enter any num: "))
nn=n+n
nnn=n+n+n
print(int(n)+int(nn)+int(nnn))

Enter any num: 10
102030


In [36]:
#    n
#   +n
# +nnn
a = int(input("Input an integer : "))
n1 = int( "%s" % a )
n2 = int( "%s%s" % (a,a) )
n3 = int( "%s%s%s" % (a,a,a) )
print (n1+n2+n3)


Input an integer : 5
615


In [34]:
print(abs.__doc__)

Return the absolute value of the argument.


In [38]:
#calendar
import calendar
y = int(input("Input the year : "))
m = int(input("Input the month : "))
print(calendar.month(y, m))


Input the year : 2000
Input the month : 3
     March 2000
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



In [41]:
print("""
a string that you "don't" have to escape
This
is a  ....... multi-line
heredoc string --------> example
""")



a string that you "don't" have to escape
This
is a  ....... multi-line
heredoc string --------> example



In [42]:
#count days between two days
from datetime import date
f_date = date(2014, 7, 2)
l_date = date(2014, 7, 11)
delta = l_date - f_date
print(delta.days)


9


In [47]:
from math import pi 

r= 6.0
V= 4.0/3.0*pi* r**3
print('The volume of the sphere is: ',V)


The volume of the sphere is:  904.7786842338603


In [49]:
def difference(n):
    if n <= 17:
        return 17 - n
    else:
        return (n - 17) * 2 

print(difference(22))
print(difference(14))
print(difference(50))


10
3
66


In [50]:
def near_thousand(n):
      return ((abs(1000 - n) <= 100) or (abs(2000 - n) <= 100))
print(near_thousand(1000))
print(near_thousand(900))
print(near_thousand(800))   
print(near_thousand(2200))
print(near_thousand(1400))


True
True
False
False
False


In [51]:
def sum_thrice(x, y, z):
     sum = x + y + z
     if x == y == z:
      sum = sum * 3
     return sum
print(sum_thrice(1, 2, 3))
print(sum_thrice(3, 3, 3))


6
27


In [57]:
def new_string(str):
  if len(str) >= 2 and str[:2] == "Is":
    return str
  return "Is" + str

print(new_string("Array"))
print(new_string("IsEmpty"))

IsArray
IsEmpty


In [62]:
def news(str):
    if len(str) >=2 and str[:2] == "Is":
        return str
    return "Is" + str

print(news("Hurray"))

IsHurray


In [63]:
def larger_string(str, n):
   result = ""
   for i in range(n):
      result = result + str
   return result

print(larger_string('abc', 2))
print(larger_string('.py', 3))


abcabc
.py.py.py


In [69]:
def rep_print(str,n):
    r=""
    for i in range(n):
        r = r+str
    return r

print(rep_print('abc',3))


abcabcabc


In [70]:
stri = str(input("Enter string and iterations: "))
itr = int(input())
print(stri*itr)

Enter string and iterations: adi
5
adiadiadiadiadi


In [75]:
#to check given number is even or odd
n1 = int(input("Enter any number: "))
if n1%2==0 :
   print("Even")
else :
   print("Odd")

Enter any number: 6
Even


In [79]:
def lc(nums):
    count = 0
    for n in nums:
      if n == 4:
        count = count + 1
    return count

print(lc([1,4,5,6,4,7,4,8,4]))

4


In [83]:
#https://www.w3resource.com/python-exercises/
def susb(str,n):
    flen=2
    if flen>len(str):
        flen=len(str)
    susb=str[:flen]
    
    result=""
    for i in range(n):
      result=result+susb
    return result
print(susb('A',3))

AAA


In [107]:
vowel = ('a','e','i','o','u')
def vow(str):
  n=len(str)
 
  for i in range(n):
     result=""
     if str[i] not in vowel:
        result=result+str[i]
        #print(str[i])
       # result+=str[i])
  return result


print(vow("ABCDEFGHI"))



TypeError: str() takes at most 3 arguments (5 given)

In [86]:
def is_vowel(char):
    all_vowels = 'aeiou'
    return char in all_vowels
print(is_vowel('c'))
print(is_vowel('e'))


False
True


In [137]:

#str(input("enter string: "))

def anti_vowel(str):
    newstr = str.lower()
    vowels = ('a', 'e', 'i', 'o', 'u')
    
    for x in str.lower():
        if x in vowels:
            newstr = newstr.replace(x,"")

    return newstr


print(anti_vowel("Aditya"))    

dty


In [138]:
string = "a quick brown fox jumps over a lazy dog"
vowel = "aeiou"

for char in string:
   if char not in vowel:
       print(char)

 
q
c
k
 
b
r
w
n
 
f
x
 
j
m
p
s
 
v
r
 
 
l
z
y
 
d
g


In [139]:
def is_group_member(group_data, n):
    for value in group_data:
        if n == value:
            return True
    return False
print(is_group_member([1, 5, 8, 3], 3))
print(is_group_member([5, 8, 3], -1))


True
False


In [142]:
def ingrp(grpdata,n):
    for v in grpdata:
        if n ==v:
            return True
    return False
print(ingrp([1,2,3,4,5], 4))

True


In [143]:
def histogram( items ):
    for n in items:
        output = ''
        times = n
        while( times > 0 ):
          output += '*'
          times = times - 1
        print(output)

histogram([2, 3, 6, 5])


**
***
******
*****


In [147]:
def concat_list(list):
    result=''
    for element in list:
        result +=str(element)
    return result

print(concat_list([1,2,3,4,5,6,'adi']))


123456adi


In [150]:
numbers = [    
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 237, 978, 328, 615, 953, 345, 
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 237, 866, 950, 626, 949, 687, 217, 
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 237, 742, 717, 
    958,743, 527
    ]

for x in numbers:
    if x == 237:
        print(x)
        break;
    elif x % 2 == 0:
        print(x)

386
462
418
344
236
566
237


In [162]:
color_list_1 = set(["White", "Black", "Red"]) 
color_list_2 = set(["Red", "Green"])
result=''
for color in color_list_1:
    if color in color_list_2:
        continue;
    else:
        print(color)
    

White
Black


In [163]:
color_list_1 = set(["White", "Black", "Red"]) 
color_list_2 = set(["Red", "Green"])
print(color_list_1.difference(color_list_2))

{'White', 'Black'}


In [170]:
#(h*b)/2
height=int(input("Enter height & width: "))
width=int(input())
print("Area of a triangle with height: "+str(height)+" and width: "+str(width)+" = "+str((height*width)/2))

Enter height & width: 5
5
Area of a triangle with height: 5 and width: 5 = 12.5


In [171]:
def sum(x, y, z):
    if x == y or y == z or x==z:
        sum = 0
    else:
        sum = x + y + z
    return sum

print(sum(2, 1, 2))
print(sum(3, 2, 2))
print(sum(2, 2, 2))
print(sum(1, 2, 3))


0
0
0
6


In [177]:
def sum(x,y):
    sum=x+y
    if sum in range(15,20):
        return 20
    else:
        return sum
    

print(sum(10,11))
print(sum(10,6))

21
20


In [183]:
def personal_details():
    name, age = "Aditya", 30
    address = "Pune, Maharashtra, India"
    print("Name: {}\nAge: {}\nAddress: {}".format(name, age, address))

personal_details()


Name: Aditya
Age: 30
Address: Pune, Maharashtra, India


In [185]:
x, y = 7, 5
result = x * x + 2 * x * y + y * y
print("({} + {}) ^ 2) = {}".format(x, y, result))

(7 + 5) ^ 2) = 144


In [190]:
#Write a Python program to compute the future value of a specified principal amount, rate of interest, and a number of years. Go to the editor
#Test Data : amt = 10000, int = 3.5, years = 7
#Expected Output : 12722.79

amt,roi,time = 10000,3.5,7
interest=(amt*roi*time)/100
print("Total amount: ", (amt+interest))
print("Interest is: ",interest)

Total amount:  12450.0
Interest is:  2450.0


In [192]:
import math

p1=[4,0]
p2=[6,5]
distance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
print(distance)

5.385164807134504


In [195]:
import os.path
open('abc.txt', 'w')
print(os.path.isfile('abc.txt'))

True


In [202]:
def char_frequency(str1):
    dict = {}
    for n in str1:
        keys = dict.keys()
        if n in keys:
            dict[n] += 1
        else:
            dict[n] = 1
    return dict
print(char_frequency('sanjayjoshiisagemofaperson'))

{'s': 4, 'a': 4, 'n': 2, 'j': 2, 'y': 1, 'o': 3, 'h': 1, 'i': 2, 'g': 1, 'e': 2, 'm': 1, 'f': 1, 'p': 1, 'r': 1}


In [203]:
def string_both_ends(str):
  if len(str) < 2:
    return ''

  return str[0:2] + str[-2:]

print(string_both_ends('w3resource'))
print(string_both_ends('w3'))
print(string_both_ends('w'))
print(string_both_ends('aditya'))


w3ce
w3w3

adya


In [205]:
def change_char(str1):
  char = str1[0]
  str1 = str1.replace(char, '$')
  str1 = char + str1[1:]

  return str1

print(change_char('restartors'))


resta$to$s


In [1]:
def add_string(str1):
  length = len(str1)

  if length > 2:
    if str1[-3:] == 'ing':
      str1 += 'ly'
    else:
      str1 += 'ing'

  return str1
print(add_string('ab'))
print(add_string('abc'))
print(add_string('string'))


ab
abcing
stringly


# Lists

In [5]:
def slist(items):
    sum_numbers = 0
    for x in items:
        sum_numbers += x
    return sum_numbers
print(slist([1,2,-8,10,2]))

7


In [9]:
#Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples.
def last(n): return n[-1]

def sort_list_last(tuples):
  return sorted(tuples, key=last)

print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))


[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [10]:
#Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples.
def last(n): return n[-1]

def sortList(tuples):
    return sorted(tuples, key=last)

print(sortList([(2,3),(2,9),(2,5),(2,8),(2,1)]))

[(2, 1), (2, 3), (2, 5), (2, 8), (2, 9)]


In [15]:
# Write a Python program to remove duplicates from a list.
a = [10,20,30,20,10,50,60,40,80,50,40]

set_dup_items = set()
list_uniq_items = []
for x in a:
    if x not in set_dup_items:
        uniq_items.append(x)
        set_dup_items.add(x)

print(set_dup_items)
print(uniq_items)


{40, 10, 80, 50, 20, 60, 30}
[10, 20, 30, 50, 60, 40, 80, 10, 20, 30, 50, 60, 40, 80, 10, 20, 30, 50, 60, 40, 80, 10, 20, 30, 50, 60, 40, 80]


In [20]:
lst = []
if not lst:
  print("List is empty")
else:
    print("Not Empty")

List is empty


In [23]:
lst = [1,2,'d',4,5,'g']
newlst=list(lst)
print(newlst)

[1, 2, 'd', 4, 5, 'g']


# Dictionaries

In [24]:
import operator
d = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
print('Original dictionary : ',d)
sorted_d = sorted(d.items(), key=operator.itemgetter(0))
print('Dictionary in ascending order by value : ',sorted_d)
sorted_d = sorted(d.items(), key=operator.itemgetter(0),reverse=True)
print('Dictionary in descending order by value : ',sorted_d)


Original dictionary :  {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
Dictionary in ascending order by value :  [(0, 0), (1, 2), (2, 1), (3, 4), (4, 3)]
Dictionary in descending order by value :  [(4, 3), (3, 4), (2, 1), (1, 2), (0, 0)]


In [38]:
#Write a Python script to sort (ascending and descending) a dictionary by value.
import operator
d={1:2,2:4,5:3,4:6,6:9,3:4,2:0}
sotred_list = sorted(d.items(), key=operator.itemgetter(0))
print("sorted list: ", sotred_list)
d.update({11:7})
print("updated list: ", d)
sotred_list = sorted(d.items(), key=operator.itemgetter(0))
print("updated sorted list: ", sotred_list)


sorted list:  [(1, 2), (2, 0), (3, 4), (4, 6), (5, 3), (6, 9)]
updated list:  {1: 2, 2: 0, 5: 3, 4: 6, 6: 9, 3: 4, 11: 7}
updated sorted list:  [(1, 2), (2, 0), (3, 4), (4, 6), (5, 3), (6, 9), (11, 7)]


In [48]:
# Write a Python program to concatenate following dictionaries to create a new one.
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
dic4 = {}
for d in (dic1, dic2, dic3): 
    dic4.update(d)
print(dic4)

def is_key_present(x):
    if x in dic4:
        print("Key present")
    else:
        print("Key not present")

is_key_present(5)
is_key_present(15)


def is_value_present(x):
    if x in dic4.values():
        print("Value present")
    else:
        print("Value not present")

is_value_present(50)
is_value_present(15)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
Key present
Key not present
Value present
Value not present


In [51]:
# Write a Python program to iterate over dictionaries using for loops.
d = {'x': 10, 'y': 20, 'z': 30} 
for dict_key, dict_value in d.items():
    print(dict_key,'->',dict_value)


x -> 10
y -> 20
z -> 30


In [1]:
from collections import Counter
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
d = Counter(d1) + Counter(d2)
print(d)


Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})


In [2]:
import itertools      
d ={'1':['a','b'], '2':['c','d'], '3':['e','f']}
for combo in itertools.product(*[d[k] for k in sorted(d.keys())]):
    print(''.join(combo))


ace
acf
ade
adf
bce
bcf
bde
bdf


In [3]:
num = {'n1': [2, 3, 1], 'n2': [5, 1, 2], 'n3': [3, 2, 4]}
sorted_dict = {x: sorted(y) for x, y in num.items()}
print(sorted_dict)

{'n1': [1, 2, 3], 'n2': [1, 2, 5], 'n3': [2, 3, 4]}


In [4]:
student_list = {'S  001': ['Math', 'Science'], 'S    002': ['Math', 'English']}
print("Original dictionary: ",student_list)
student_dict = {x.translate({32: None}): y for x, y in student_list.items()}
print("New dictionary: ",student_dict)

Original dictionary:  {'S  001': ['Math', 'Science'], 'S    002': ['Math', 'English']}
New dictionary:  {'S001': ['Math', 'Science'], 'S002': ['Math', 'English']}


In [5]:
def sum_math(list_of_dicts):
    for d in list_of_dicts:
        n1 = d.pop('V')
        n2 = d.pop('VI')
        d['V+VI'] = (n1 + n2)/2
    return list_of_dicts 
student_details= [
  {'id' : 1, 'subject' : 'math', 'V' : 70, 'VI' : 82},
  {'id' : 2, 'subject' : 'math', 'V' : 73, 'VI' : 74},
  {'id' : 3, 'subject' : 'math', 'V' : 75, 'VI' : 86}
]
print(sum_math(student_details))

[{'id': 1, 'subject': 'math', 'V+VI': 76.0}, {'id': 2, 'subject': 'math', 'V+VI': 73.5}, {'id': 3, 'subject': 'math', 'V+VI': 80.5}]


In [8]:
n=5;
for i in range(n):
    for j in range(i):
        print ('* ', end="")
    print('')

#for i in range(n,0,-1):
#    for j in range(i):
#        print('* ', end="")
#    print('')


* 
* * 
* * * 
* * * * 


In [13]:
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20) # Declaring the tuple
count_odd = 0
count_even = 0
for x in numbers:
        if not x % 2:
             count_even+=1
        else:
    	     count_odd+=1
print("Number of even numbers :",count_even)
print("Number of odd numbers :",count_odd)

Number of even numbers : 10
Number of odd numbers : 10


In [15]:
for x in range(6):
    if (x == 3 or x==6):
        continue
    print(x,end=' ')
print("\n")

0 1 2 4 5 



## Numpy Practices

In [16]:
import numpy as np
print(np.__version__)

1.14.3


In [18]:
import numpy as np
l = [[12.23, 13.32], [100, 36.32]]
print("Original List:",l)
a = np.array(l)
print("One-dimensional numpy array: ",a)

Original List: [[12.23, 13.32], [100, 36.32]]
One-dimensional numpy array:  [[ 12.23  13.32]
 [100.    36.32]]


In [29]:
import numpy as np
x =  np.arange(2, 14).reshape(4,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
